name: deploy_new_code_to_prod
on:
  push:
    branches:
      - main    #Allow only develop branch to run this gitlab pipeline
jobs:
  deploy:
    name: Update code to prod server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3				#Checkout from the branch
      - name: Update file via ssh password
        uses: appleboy/scp-action@master			#Copy the repo files to the server
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }}
          source: "*"
          target: "/var/www/html/"	#Destination path of the server
